modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"

[[mods]]
modId="jjoons_science"
version="0.01"
displayName="Jjoon's science"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="by Jjoon"
description="Minecraft makes more scientific!"

[[dependencies.jjoons_science]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




